client_config_backend: settings
client_config:
  client_id: 841487988678-78uje2p6h4alrhasc5e98qadlh4o3fvq.apps.googleusercontent.com
  client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install